# =============================================
# ========== Pyright
# =============================================
[tool.pyright]
# SEE: Pyright: https://github.com/microsoft/pyright/blob/main/docs/configuration.md
# SEE: Basedpyright: https://docs.basedpyright.com/dev/configuration/config-files
# ==================== Environment Options ====================
# include = ["src"]
exclude = [
  "**/.git",
  "**/.idea",
  "**/.vscode",
  "**/.cache",
  "**/.venv",
  "**/__pycache__",
  "**/.mypy_cache",
]

# strict  = []
# extends = ""
# defineConstant = { "DEBUG": true }
# stubPath = ""
# extraPaths = []

# verboseOutput = false

# pythonPlatform = "Darwin"  # values: "Windows" | "Darwin" | "Linux" | "All"
# pythonVersion = ""

# executionEnvironments = []

useLibraryCodeForTypes = true


# ==================== Type Evaluation Settings ====================
# strictListInference        = false
# strictSetInference         = false
# strictDictionaryInferencet = false

# strictParameterNoneValue   = true

# analyzeUnannotatedFunctions = true

# deprecateTypingAliases = true
# disableBytesTypePromotions = true
# enableExperimentalFeatures = false

# ---------- Basedpyright Exclusive Settings
# strictGenericNarrowing = true
# enableBasedFeatures = false

# ---------- Discouraged Settings
enableTypeIgnoreComments = true
# enableReachabilityAnalysis = false


# ==================== Diagnostics ====================
typeCheckingMode = "recommended"  # values: "off" | "basic" | "strict" | "recommended" | "all"
# ignore = []

# ---------- Type Check Rule Overrides [Not All Settings Shown]
# Values: "error" | "warning" | "information" | "hint" | "none" | boolean
reportMissingImports = false  # by flake8
